### PR TITLE
feature-1-registration

### LINKED ISSUE #1: [Feature 1] Registration
Registers a user. 
- Pick whether the user or dealership (radio button)
- Enter email (show error if email already exists)
- Enter the password twice (show error if passwords don't match)
- Enter name
- if dealership enter location (show error if invalid pincode)
- Error if any fields are blank upon submission
- Submit button

### PR DESCRIPTION
**Pull request by manav393**
Completed user registration while implementing clean architecture techniques taught in class. 
- Users can now register on the application
- There are two types of users - Individual and Dealership.
- Users can choose which user they are upon registration
- Dealerships have location which is prompted upon submission of form
- Individual users don't have this location. It is stored as null
- The final user object is stored in the database, which is users.csv

### CODE REVIEW

**Review by RyanSafa — COMMENTED** [review]
Nice work Manav! Great implementation of clean architecture. I just have a few minor comments. 

`    private final List<Integer> listings = new ArrayList<>();
`

I don't think that the listings array in Users should be final, because we would be updating it whenever creates a new listing. 

I don't think we need to implement MVC/MVVM architecture in the register use case, as it's pretty simple UI. But in the future for displaying Listings and filtering, we might opt to use that type of architecture.

Also, there are no javadocs and test. I'll just make a new issue where we can add these later on after we get the further into the project.

**Comment by manav393** [comment]
Hey Ryan, thank you for your insightful comments about implementing MVC/MVVM architecture and perhaps we can talk more about it in our next meeting, but I think the current implementation is good for the future of our project.

As for your comment about not making the listings final,

> `private final List<Integer> listings = new ArrayList<>();`

Setting the listings as a final array is done so that the variable listings cannot refer to anything else. However, the members of the array can still be modified. Only the reference is final.

**Comment by RyanSafa** [comment]
> Setting the listings as a final array is done so that the variable listings cannot refer to anything else. However, the members of the array can still be modified. Only the reference is final.

Ah, makes sense. Everything looks good to me. I'll approve it.

**Review by RyanSafa — APPROVED** [review]

**Review by jyotiraditya09 — APPROVED** [review]
Looks nice. For the Listing entity, we should create the constructor and other methods once we get to the Create Listing use case.

**Pull request merged**
